### ISSUE TITLE
suggestion: refactor task parser to add multiples todo to subtasks

### ISSUE THREAD

**Issue by deamonTux** [ben-sentenac/taskify#1]
Hello it could cool to have a the possibility to add todos to sub-tasks,
for now we can edit the md file like:
```md
# Task1:TaskName
- [ ] subtask 
```
what if we could do instead:
```md
# Task 1: Taskname 
       [ ] subtask Description 
            [ ] todo 1
            [ ] todo 2
```
Please, let me now if you're interested in.

**Comment by ben-sentenac** [comment]
Yes of course , i plan doing this, but i don't have time rigtht now
